
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
#    ?????????
#  mvc:
#    static-path-pattern: /source/**
#  web:
#    resources:
#      static-locations: classpath:/source/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml